version: 2
jobs:
  unit-test:
    docker:
      - image: awav/tensorflow:1.12.0
    steps:
      - checkout
      - run: python setup.py install
      - run: pytest -v -W ignore::UserWarning --durations=10 --cov=./gpflow -m "not notebooks" ./tests
  notebook-test:
    docker:
      - image: awav/tensorflow:1.12.0
    environment:
      CI: notebooks
    steps:
      - checkout
      - run: python setup.py install
      - run: pytest -v -n auto -W ignore::UserWarning --durations=10 --cov=./gpflow -m notebooks ./tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit-test
      - notebook-test