runtest: &runtest
  steps:
    - checkout
    - run: env
    - run: python setup.py install
    - run: pytest -v -W ignore::UserWarning --durations=10 ${PYTEST_FILTER} --cov=./gpflow --cov-report=xml ./tests
    - codecov/upload:
        file: ./coverage.xml

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.1

jobs:
  unit-test:
    <<: *runtest
    docker:
      - image: awav/tensorflow:1.12.0
        environment:
          PYTEST_FILTER: -m 'not notebooks'

  notebook-test:
    <<: *runtest
    docker:
      - image: awav/tensorflow:1.12.0
        environment:
          PYTEST_FILTER: -m notebooks

workflows:
  # version: 2
  build_and_test:
    jobs:
      - unit-test
      - notebook-test
